version: '3.9'

services:
  postgres:
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"

  api:
    depends_on:
      - postgres
    build:
      context: api
    ports:
      - "8000:8000"
